# Generated by Django 2.2.3 on 2019-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
